#!/bin/sh
EPMD_ROOT=./%%ERTS_VSN%%/bin
LOG_BASE="./var/log/rabbitmq"
./bin/post_install.sh
./sbin/rabbitmq-server

exit_code=1
tries=0

while [ $exit_code -gt 0 ]
do
    grep 'broker running\|already running' "${LOG_BASE}"/erlang.out > /dev/null
    exit_code=$?
    # exit after 10 attempts
    tries=$((tries+1))
    if [ $tries -eq 10 ]
    then
        exit 1
    fi
    sleep 1
done

exit 0